mock:
  server:
    address: test
  image:
    catalog:
      url: https://test:9443/imagecatalog

integrationtest:
  threadCount: 8
  parallel: classes
  defaultBlueprintName: hdp-small-default
  outputdir: /it
  command: suites
  cleanup:
    cleanupBeforeStart: false
